void prs_error (const char *template, ...);
void prs_end (const char *template, ...);
void prs_stderr (const char *template, ...);
void prs_msg (const char *template, ...);
void *prs_malloc ();
void InitVariables ();
void var();
void ReadVariables ();
void ReadVarFile ();
void ListVariables ();
FILE *prs_open ();
FILE *prs_openi ();
FILE *prs_opend ();
FILE *prs_opena ();
long switches ();
void PrintUsage ();
void DumpParameters ();
void DumpSources ();
void ListVariablesIDL ();
void SetGlobalVariables ();
void FillCPUGrid ();
void TestEndian ();
void splitgrid();
void repartition();
void ScanGridFile ();
void primefactors ();
boolean buildprime ();
void GridFileError (long linenumber, char *filename, const char *template, ...);
FluidPatch *CreateFluidPatch ();
ScalarField *CreateScalarField ();
VectorField *CreateVectorField ();
void FreeScalarField ();
void FreeVectorField ();
InterfaceFlux *CreateInterfaceFlux ();
void FreeInterfaceFlux ();
void FreeFluidPatch ();
void WriteWorkArray ();
void WriteVectorField ();
void WriteScalarField ();
void WriteFluid ();
void InitialCondition ();
void ReallocateSpaceForCurrentFluidPatch ();
void CreateCurrentFluidPatch ();
void SendToCurrent ();
void ReallocateSpaceForSecondaryFluidPatch ();
void CreateSecondaryFluidPatch ();
void SendToSecondary ();
void ComputeExternalPotential ();
void ResetFaceFluxesLevel ();
void ResetFaceFluxes ();
void CurrentToPatch ();
real Mass ();
real TotalMass ();
void ApplyBoundaryConditions ();
void ItereLevel ();
real RecursiveIteration ();
void InitWholeHierarchy ();
real Momentum ();
real TotalMomentum ();
void ConservativeUpdate ();
void DiffusionUpdate ();
void MassUpdate ();
real ItereRS ();
void GetStar_TWOSHOCKS ();
void GetStar_TWORAREFACTIONS ();
void GetStar_ITERATIVE ();
void GetStar_PRESSURELESS ();
real TVDslope();
real TVDslope2();
real minmod();
real superbee();
void FillBeam ();
void FillBeam2 ();
void FillFluxes ();
void FillDiffFluxes ();
void FillDiffFluxes2 ();
void gfo ();
void gfo_adiab ();
void plm ();
void plm_adiab ();
real sgn();
real wavelimit();
void HydroKernel ();
void DiffusionKernel ();
void DiffPresKernel ();
void Compute_Fluxes_Iso ();
void Compute_Fluxes_pressureless1 ();
void Compute_Fluxes_pressureless2 ();
void Compute_Fluxes_pressureless3 ();
void Compute_Fluxes_Diffusion ();
void Compute_Fluxes_DiffPres ();
void CorrectFluxesFromFinerLevel ();
void Source ();
void DustDiffusion ();
boolean boundary ();
real CourantLimit ();
real CourantLimitGlobal ();
void ViscousStress ();
void ApplyViscousStress ();
void prs_exit ();
void getgridsize ();
void getgridsizes ();
void WriteDescriptor ();
void BuildCommunicators ();
long StripCommunicators ();
void release_com ();
void DestroyCom ();
void DestroyHash ();
boolean CubeIntersect ();
void BlockButcher ();
boolean CubeIntersectPeriodic ();
void Comm_Alloc ();
void ExecCommSame ();
void ExecCommSameVar ();
void ExecCommUpVar ();
void ExecCommUpVarLIL ();
void ExecCommDownFlux ();
void ExecCommDownMean ();
void ExecCommUp ();
void ExecComm ();
void Write ();
void CheckBC ();
void TrueBC ();
void TrueBC_fp ();
void SetOverlapFlag ();
void ExecCommFlux ();
void MonitorConservative ();
void setfpe ();
void handfpe();
void GridBuild ();
void MakeDir ();
void ReadGrids ();
void CommAll ();
real Torque();
void TotalTorque();
void MonitorTorque ();
void MonitorTorqueZ ();
void keplerian_create();
real keplerian_init();
real keplerian_dust_init();
real keplerian_pot();
real keplerian_comm();
real keplerian_boundary();
void GridAbs ();
void GridPos ();
void ReadField ();
void merge ();
FILE *prs_openrd();
FILE *prs_openr();
void merge_field ();
void setout ();
void ConstructGrids ();
void refine ();
void refine_field();
void FillSources ();
void FillSources2 ();
void FillDiffSources_Dust ();
void FillDiffSources_Gas ();
void memcpystride ();
void multarray ();
void arraymult ();
void FillSlopes ();
void mpiwarning ();
void AdjustBeamBoundaries ();
void addinitcode ();
void testdoubledefined ();
void testundef ();
void findcodeinit ();
void setinitcodes ();
void addpotcode ();
void testpotdoubledefined ();
void testundefpot ();
void findcodepot ();
void setpotcodes ();
void PressureCorrection ();
void SetCommSource ();
long nbvariables ();
long dimfield ();
void WriteCommSource ();
void WriteCommDest ();
PressureFaces *CreatePressureFaces ();
void FreePressureFaces ();
real KineticEnergy ();
real TotalKineticEnergy ();
void MonitorKineticEnergy ();
real TorqueStockholm ();
void ApplyStockholmBoundaryConditions ();
void ApplyStockholmBoundaryConditions2 ();
void DiskRadialDrift();
real **multiple_alloc_1D ();
void ReserveForBeam_PLM ();
void ReserveForSecondaryBeam_PLM ();
void ReserveForTertiaryBeam_PLM ();
void ReserveForWorkPatch ();
void ReserveForSecondaryWorkPatch ();
void MakeBeam_PLM ();
void AllocBeam_PLM ();
void AllocSecondaryBeam_PLM ();
void AllocTertiaryBeam_PLM ();
void ReserveForBeam_MUSCL ();
void MakeBeam_MUSCL ();
void AllocBeam_MUSCL ();
void MakeCurrentFluidPatch ();
void MakeSecondaryFluidPatch ();
void Divergence ();
void FindBestSubcycling ();
void EvaluateBaseStepRatio ();
void EvaluateLevelCost ();
real SubCycleCost ();
void pInfo (const char *template, ...);
void pWarning (const char *template, ...);
void pError (const char *template, ...);
void ResetChronometer ();
void ReadChronometer ();
void FlushLog ();
void FlushInfo ();
void checkpara ();
int fselect ();
long GlobalInit ();
void ReadDefaultInOut ();
void SubsDef ();
void ExtractPath ();
FILE *FindGridFile ();
void DumpInitCode ();
void DumpPotCode ();
void ReadRedefined ();
void ParseRedefinedOptions ();
void muscl();
void Predictor ();
void convert_coord ();
void Ray_Integrate ();
void Ray_System_BoundingBox ();
void Ray_Tracing ();
void make_central_star ();
void make_planet ();
void make_background_stars ();
void AllocateSqueezedArrays ();
void CreateSqueezedArrays ();
void CreateAllSqueezedArrays ();
void HydroStatPrepare ();
SqueezedField *AllocateSqueezedArray ();
void WriteHydroStat ();
void WriteSqueezedField ();
void SetCenteredDensity ();
void SetInterfaceQuantities ();
void CorrectSourceTerm ();
void ForAllPatches ();
void SetToZero ();
void ResetPatch ();
real comm_adapt ();
real CorrKeplerianFlux ();
real IC_Average ();
real IC_2D_Mean ();
real IC_Corr ();
real IC_Density ();
real IC_Vrad ();
real IC_Vazimuth ();
real IC_Vcolatitude ();
real IC_Energy ();
real GetInitialValue ();
real MassFluxRotating ();
real MassFluxSolidRotation ();
real MassFluxInertial ();
real MomentumFluxRotating ();
real MomentumFluxInertial ();
real MomentumFluxSolidRotation ();
void cpTriplet ();
void resetTriplet ();
void swapl ();
void InitFluxCorrectionMeridian ();
real IC_Pressure ();
real IC_PressureByRad ();
boolean SquareIntersect ();
void GetMaxLevProjectedMeridian ();
void MultiFluid ();
void SetFluidProperties ();
void FluidCoupling ();
