/********************************/
/*                              */
/* This file is created         */
/* automatically during         */
/* compilation. Do not edit.    */
/* See perl script              */
/* "varsubst" for details   */
/*                              */
/********************************/
real	DT;
char	OUTPUTDIR[512];
long	NTOT;
long	NINTERM;
long	SIZE1;
long	SIZE2;
long	SIZE3;
long	GHOSTFILLINGORDER;
char	DIM1SPACING[512];
char	DIM2SPACING[512];
char	DIM3SPACING[512];
real	RANGE1LOW;
real	RANGE1HIGH;
real	RANGE2LOW;
real	RANGE2HIGH;
real	RANGE3LOW;
real	RANGE3HIGH;
real	CFLSECURITY;
real	GAMMA;
long	NDIM;
char	COORDTYPE[512];
char	COORDPERMUT[512];
boolean	INHIBREFDIM1;
boolean	INHIBREFDIM2;
boolean	INHIBREFDIM3;
boolean	DIM1PERIODIC;
boolean	DIM2PERIODIC;
boolean	DIM3PERIODIC;
char	GRIDFILE[512];
char	RIEMANNSOLVER[512];
char	DUSTSOLVER[512];
char	METHOD[512];
char	SLIMITER[512];
char	INITCODE[512];
char	POTENTIALCODE[512];
char	CONDLIM1[512];
char	CONDLIM2[512];
char	CONDLIM3[512];
char	FIXEDPOTENTIAL[512];
real	SMALLESTDENSRATIO;
boolean	KEPLERIAN;
real	OMEGAFRAME;
real	ASPECTRATIO;
real	SIGMASLOPE;
real	FLARINGINDEX;
real	SIGMA0;
real	MASSTAPER;
real	VISCOSITY;
real	PLANETMASS;
real	SMOOTHING;
real	GRIDFRICTION1;
real	GRIDFRICTION2;
real	GRIDFRICTION3;
boolean	EXTERNALPOTENTIAL;
boolean	MERIDIANCORRECTION;
real	DRIFTVELOCITY;
real	CS;
real	INCLINATION;
char	SUBCYCLING[512];
char	NODAMPING[512];
char	CONSTSTOKES[512];
char	POTENTIALHYDROSTAT[512];
char	INITHYDROSTAT[512];
char	SYMDIM_EQ[512];
char	CORRDIM_EQ[512];
char	FLUIDS[512];
real	COUPLING;
real	STOKESNUMBER;
real	DUSTSIZE;
real	DUSTDENSFLOOR;
boolean	DUSTDIFF;
long	DIFFMODE;
real	DUSTTOGAS;
real	NOISE;
long	OUTPUTATREFINEMENT;
long	FinestLevel;
real	SMRATIO;
